pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the source code...'
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']], // Replace 'main' with your default branch
                    userRemoteConfigs: [[url: 'https://github.com/Shivamkumar1223/Teraform-test.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'npm install'
                sh 'npm run build'
            }
        }
    }

    post {
        success {
            echo 'Build and Checkout Successful!'
        }
        failure {
            echo 'Build or Checkout Failed. Check the logs.'
        }
    }
}
