pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Verify Jenkinsfile') {
            steps {
                echo 'Verifying Jenkinsfile exists...'
                sh '''
                    cd /tmp
                    rm -rf test-repo
                    git clone https://github.com/Shivamkumar1223/Teraform-test.git test-repo
                    cd test-repo
                    ls -l Jenkinsfile
                '''
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building the application...'
                sh 'npm install'
                sh 'npm run build'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}
